import asyncio

from aiogram import Bot, Dispatcher, types, F
from aiogram.client.default import DefaultBotProperties
from aiogram.enums import ParseMode

'''
import sys
import os

current_dir = os.path.dirname(os.path.abspath(__file__))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)
'''

TOKEN = ""

bot = Bot(TOKEN,
          default=DefaultBotProperties(parse_mode=ParseMode.HTML)
)
dp = Dispatcher()


async def main():
    await bot.delete_webhook(drop_pending_updates=True)  # Skip colected updates
    await dp.start_polling(bot)


if __name__ == '__main__':
    asyncio.run(main())


print(bot.__dict__)
"""
{'session': <aiogram.client.session.aiohttp.AiohttpSession object at 0x7f3e6a2b30d0>,
 'default': DefaultBotProperties(parse_mode=None,
                                 disable_notification=None,
                                 protect_content=None,
                                 allow_sending_without_reply=None,
                                 link_preview=None,
                                 link_preview_is_disabled=None,
                                 link_preview_prefer_small_media=None,
                                 link_preview_prefer_large_media=None,
                                 link_preview_show_above_text=None,
                                 show_caption_above_media=None),
 '_Bot__token': '1690656566:AAH1aWeuR*****Ps9yjU_UfnstKxr5ALXUcY4',
 '_me': None}
"""


print(dir(bot))
"""
['_Bot__aiofiles_reader',
'_Bot__download_file',
'_Bot__download_file_binary_io',
'_Bot__token',
'__aenter__',
'__aexit__',
'__call__',
'__class__',
'__delattr__',
'__dict__',
'__dir__',
'__doc__',
'__eq__',
'__format__',
'__ge__',
'__getattribute__',
'__getstate__',
'__gt__',
'__hash__',
'__init__',
'__init_subclass__',
'__le__',
'__lt__',
'__module__',
'__ne__',
'__new__',
'__reduce__',
'__reduce_ex__',
'__repr__',
'__setattr__',
'__sizeof__',
'__str__',
'__subclasshook__',
'__weakref__',
'_me',
'add_sticker_to_set',
'answer_callback_query',
'answer_inline_query',
'answer_pre_checkout_query',
'answer_shipping_query',
'answer_web_app_query',
'approve_chat_join_request',
'ban_chat_member',
'ban_chat_sender_chat',
'close',
'close_forum_topic',
'close_general_forum_topic',
'context',
'copy_message',
'copy_messages',
'create_chat_invite_link',
'create_chat_subscription_invite_link',
'create_forum_topic',
'create_invoice_link',
'create_new_sticker_set',
'decline_chat_join_request',
'default',
'delete_chat_photo',
'delete_chat_sticker_set',
'delete_forum_topic',
'delete_message',
'delete_messages',
'delete_my_commands',
'delete_sticker_from_set',
'delete_sticker_set',
'delete_webhook',
'download',
'download_file',
'edit_chat_invite_link',
'edit_chat_subscription_invite_link',
'edit_forum_topic',
'edit_general_forum_topic',
'edit_message_caption',
'edit_message_live_location',
'edit_message_media',
'edit_message_reply_markup',
'edit_message_text',
'edit_user_star_subscription',
'export_chat_invite_link',
'forward_message',
'forward_messages',
'get_available_gifts',
'get_business_connection',
'get_chat',
'get_chat_administrators',
'get_chat_member',
'get_chat_member_count',
'get_chat_menu_button',
'get_custom_emoji_stickers',
'get_file',
'get_forum_topic_icon_stickers',
'get_game_high_scores',
'get_me',
'get_my_commands',
'get_my_default_administrator_rights',
'get_my_description',
'get_my_name',
'get_my_short_description',
'get_star_transactions',
'get_sticker_set',
'get_updates',
'get_user_chat_boosts',
'get_user_profile_photos',
'get_webhook_info',
'hide_general_forum_topic',
'id',
'leave_chat',
'log_out',
'me',
'pin_chat_message',
'promote_chat_member',
'refund_star_payment',
'reopen_forum_topic',
'reopen_general_forum_topic',
'replace_sticker_in_set',
'restrict_chat_member',
'revoke_chat_invite_link',
'save_prepared_inline_message',
'send_animation',
'send_audio',
'send_chat_action',
'send_contact',
'send_dice',
'send_document',
'send_game',
'send_gift',
'send_invoice',
'send_location',
'send_media_group',
'send_message',
'send_paid_media',
'send_photo',
'send_poll',
'send_sticker',
'send_venue',
'send_video',
'send_video_note',
'send_voice',
'session',
'set_chat_administrator_custom_title',
'set_chat_description',
'set_chat_menu_button',
'set_chat_permissions',
'set_chat_photo',
'set_chat_sticker_set',
'set_chat_title',
'set_custom_emoji_sticker_set_thumbnail',
'set_game_score',
'set_message_reaction',
'set_my_commands',
'set_my_default_administrator_rights',
'set_my_description',
'set_my_name',
'set_my_short_description',
'set_passport_data_errors',
'set_sticker_emoji_list',
'set_sticker_keywords',
'set_sticker_mask_position',
'set_sticker_position_in_set',
'set_sticker_set_thumbnail',
'set_sticker_set_title',
'set_user_emoji_status',
'set_webhook',
'stop_message_live_location',
'stop_poll',
'token',
'unban_chat_member',
'unban_chat_sender_chat',
'unhide_general_forum_topic',
'unpin_all_chat_messages',
'unpin_all_forum_topic_messages',
'unpin_all_general_forum_topic_messages',
'unpin_chat_message',
'upload_sticker_file']
"""

print(dp.__dict__)
"""
{
    'name': '0x7f18d7357190',
    '_parent_router': None,
    'sub_routers': [],
    'message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f450 > ,
    'edited_message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f5d0 > ,
    'channel_post': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f850 > ,
    'edited_channel_post': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f990 > ,
    'inline_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fad0 > ,
    'chosen_inline_result': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fc10 > ,
    'callback_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fd50 > ,
    'shipping_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fe90 > ,
    'pre_checkout_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531ffd0 > ,
    'poll': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c190 > ,
    'poll_answer': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c410 > ,
    'my_chat_member': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c690 > ,
    'chat_member': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c950 > ,
    'chat_join_request': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532cbd0 > ,
    'message_reaction': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532ce50 > ,
    'message_reaction_count': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d0d0 > ,
    'chat_boost': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d350 > ,
    'removed_chat_boost': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d5d0 > ,
    'deleted_business_messages': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d850 > ,
    'business_connection': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532dad0 > ,
    'edited_business_message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532dd50 > ,
    'business_message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532dfd0 > ,
    'purchased_paid_media': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532e250 > ,
    'errors': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532e4d0 > ,
    'error': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532e4d0 > ,
    'startup': < aiogram.dispatcher.event.event.EventObserver object at 0x7f18d532e750 > ,
    'shutdown': < aiogram.dispatcher.event.event.EventObserver object at 0x7f18d532e790 > ,
    'observers': {
        'message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f450 > ,
        'edited_message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f5d0 > ,
        'channel_post': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f850 > ,
        'edited_channel_post': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531f990 > ,
        'inline_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fad0 > ,
        'chosen_inline_result': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fc10 > ,
        'callback_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fd50 > ,
        'shipping_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531fe90 > ,
        'pre_checkout_query': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d531ffd0 > ,
        'poll': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c190 > ,
        'poll_answer': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c410 > ,
        'my_chat_member': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c690 > ,
        'chat_member': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532c950 > ,
        'chat_join_request': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532cbd0 > ,
        'message_reaction': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532ce50 > ,
        'message_reaction_count': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d0d0 > ,
        'chat_boost': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d350 > ,
        'removed_chat_boost': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d5d0 > ,
        'deleted_business_messages': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532d850 > ,
        'business_connection': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532dad0 > ,
        'edited_business_message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532dd50 > ,
        'business_message': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532dfd0 > ,
        'purchased_paid_media': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532e250 > ,
        'error': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532e4d0 > ,
        'update': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532e7d0 >
    },
    'update': < aiogram.dispatcher.event.telegram.TelegramEventObserver object at 0x7f18d532e7d0 > ,
    'fsm': < aiogram.fsm.middleware.FSMContextMiddleware object at 0x7f18d532ee10 > ,
    'workflow_data': {},
    '_running_lock': < asyncio.locks.Lock object at 0x7f18d532f010[unlocked] > ,
    '_stop_signal': None,
    '_stopped_signal': None,
    '_handle_update_tasks': set()
}
"""

print(dir(dp))
"""
['__class__',
'__delattr__',
'__delitem__',
'__dict__',
'__dir__',
'__doc__',
'__eq__',
'__format__',
'__ge__',
'__getattribute__',
'__getitem__',
'__getstate__',
'__gt__',
'__hash__',
'__init__',
'__init_subclass__',
'__le__',
'__lt__',
'__module__',
'__ne__',
'__new__',
'__reduce__',
'__reduce_ex__',
'__repr__',
'__setattr__',
'__setitem__',
'__sizeof__',
'__str__',
'__subclasshook__',
'__weakref__',
'_feed_webhook_update',
'_handle_update_tasks',
'_listen_update',
'_listen_updates',
'_parent_router',
'_polling',
'_process_update',
'_process_with_semaphore',
'_propagate_event',
'_running_lock',
'_signal_stop_polling',
'_stop_signal',
'_stopped_signal',
'business_connection',
'business_message',
'callback_query',
'chain_head',
'chain_tail',
'channel_post',
'chat_boost',
'chat_join_request',
'chat_member',
'chosen_inline_result',
'deleted_business_messages',
'edited_business_message',
'edited_channel_post',
'edited_message',
'emit_shutdown',
'emit_startup',
'error',
'errors',
'feed_raw_update',
'feed_update',
'feed_webhook_update',
'fsm',
'get',
'include_router',
'include_routers',
'inline_query',
'message',
'message_reaction',
'message_reaction_count',
'my_chat_member',
'name',
'observers',
'parent_router',
'poll',
'poll_answer',
'pre_checkout_query',
'propagate_event',
'purchased_paid_media',
'removed_chat_boost',
'resolve_used_update_types',
'run_polling',
'shipping_query',
'shutdown',
'silent_call_request',
'start_polling',
'startup',
'stop_polling',
'storage',
'sub_routers',
'update',
'workflow_data']
"""