# Generated by Django 4.2.13 on 2024-06-19 14:52

from django.db import migrations, models
import django.db.models.deletion
import explore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=explore.models.generate_unique_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('birth_date', models.DateField()),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Wisdom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='text')),
                ('report', models.PositiveIntegerField(default=0, verbose_name='report')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='explore.user', verbose_name='user')),
            ],
        ),
    ]
