# Generated by Django 4.2.13 on 2024-06-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wisdom',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
