services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: blog_web
    command: gunicorn wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./src:/app/src


  nginx:
    image: nginx:alpine-perl
    container_name: blog_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
