services:
  mymongo:
    image: mongo:4.4
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  dbbrowser:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_URL=mongodb://root:example@mymongo:27017/
    depends_on:
      - mymongo
    
  api:
    build: ./checker
    image: app:1.0.0
    depends_on:
      - mymongo
  
  web:
    build: ./plot
    image: plot:1.0.0
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - api

    