<<<<<<< HEAD
# Generated by Django 4.2 on 2024-11-14 13:54
=======
# Generated by Django 4.2 on 2024-11-20 09:39
>>>>>>> 4dda8f8f3c021b5f8fb12f9ee8894bb8c8e9fcea

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('main', '0003_product_rating_product_vote'),
=======
        ('main', '__first__'),
>>>>>>> 4dda8f8f3c021b5f8fb12f9ee8894bb8c8e9fcea
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
<<<<<<< HEAD
=======
                ('data', models.JSONField()),
>>>>>>> 4dda8f8f3c021b5f8fb12f9ee8894bb8c8e9fcea
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Adding date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
