<<<<<<< HEAD
# Generated by Django 4.1.13 on 2024-09-26 11:45

=======
# Generated by Django 4.2 on 2024-11-20 09:50

import django.core.validators
>>>>>>> 4dda8f8f3c021b5f8fb12f9ee8894bb8c8e9fcea
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Category')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images', verbose_name='Image')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Price')),
<<<<<<< HEAD
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories')),
                ('ingredients', models.ManyToManyField(related_name='products', to='main.ingredient')),
=======
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5.0)])),
                ('vote', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categories')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='products', to='main.ingredient')),
>>>>>>> 4dda8f8f3c021b5f8fb12f9ee8894bb8c8e9fcea
            ],
        ),
    ]
